---
templates:
- name: string
  regex: '^.*$'
- name: hostname
  regex: '^[a-zA-Z0-9][a-zA-Z0-9\-]{0,63}$'
- name: ipv4-cidr
  regex: ^((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))/([0-9]|[12][0-9]|3[0-2])$
- name: ipv4
  regex: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
- name: fqdn
  regex: '^(?:[a-zA-Z0-9][a-zA-Z0-9\-]{0,63}\.?)+$'
- name: mac
  regex: '^(?:[[:xdigit:]]{2}([-:]))(?:[[:xdigit:]]{2}\1){4}[[:xdigit:]]{2}$'
- name: ssh-key
  regex: 'ssh-rsa AAAA[0-9A-Za-z+\/]+={0,3}'
nodes:
- node: interfaces
  subnodes:
  - node: ethernet <query>
    query: ls /sys/class/net
    properties:
    - name: description
      values:
      - template: string
    - name: address
      values:
      - literal: dhcp
      - template: ipv4-cidr
    - name: hardware
      values:
      - template: mac
- node: system
  properties:
  - name: hostname
    values:
    - template: hostname
  subnodes:
  - node: dns
    properties:
    - name: domain
      values:
      - template: fqdn
    - name: nameserver
      multiple: yes
      values:
      - template: fqdn
  - node: ntp
    properties:
    - name: server
      multiple: yes
      values:
      - template: fqdn
  - node: users
    subnodes:
    - node: user <query>
      query: db users
      properties:
      - name: password
        values:
        - literal: string
      subnodes:
      - node: ssh-keys
        properties:
        - name: key
          multiple: yes
          values:
          - template: ssh-key