---
templates:
- name: string
  regex: '^.*$'
- name: hostname
  regex: '^[a-zA-Z0-9][a-zA-Z0-9\-]{0,63}$'
- name: ipv4-cidr
  regex: ^((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))/([0-9]|[12][0-9]|3[0-2])$
- name: ipv4
  regex: ^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$
- name: fqdn
  regex: '^(?:[a-zA-Z0-9][a-zA-Z0-9\-]{0,63}\.?)+$'
- name: mac
  regex: '^(?:[[:xdigit:]]{2}([-:]))(?:[[:xdigit:]]{2}\1){4}[[:xdigit:]]{2}$'
- name: ssh-key
  regex: 'ssh-rsa AAAA[0-9A-Za-z+\/]+={0,3}'
nodes:
- name: interfaces
  subnodes:
  - name: ethernet <query>
    query:
      ls: /sys/class/net
    properties:
    - key: description
      values:
      - template: string
    - key: address
      values:
      - literal: dhcp
      - template: ipv4-cidr
    - key: hardware
      values:
      - template: mac
    - key: mtu
      values:
      - range:
          from:
            inclusive: 1
          to:
            exclusive: 10000
- name: system
  properties:
  - key: hostname
    values:
    - template: hostname
  subnodes:
  - name: dns
    properties:
    - key: domain
      values:
      - template: fqdn
    - key: nameserver
      multiple: true
      values:
      - template: fqdn
  - name: ntp
    properties:
    - key: server
      multiple: true
      values:
      - template: fqdn
  - name: users
    subnodes:
    - name: user <query>
      properties:
      - key: password
        values:
        - literal: string
      subnodes:
      - name: ssh-keys
        properties:
        - key: key
          multiple: true
          values:
          - template: ssh-key