---
templates:
  string:
    regex: '.*'
  hostname:
    regex: '[a-zA-Z0-9][a-zA-Z0-9\-]{0,63}'
  ipv4-cidr:
    regex: '((?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))/([0-9]|[12][0-9]|3[0-2])'
  ipv4:
    regex: '(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
  fqdn:
    regex: '(?:[a-zA-Z0-9][a-zA-Z0-9\-]{0,63}\.?)+'
  mac:
    regex: '(?:[[:xdigit:]]{2}:)(?:[[:xdigit:]]{2}:){4}[[:xdigit:]]{2}'
  ssh-key:
    regex: 'ssh-rsa AAAA[0-9A-Za-z+/]+={0,3}'
  vid:
    range:
      lower:
        exclusive: 0
      upper:
        exclusive: 4095
nodes:
  interfaces:
    subnodes:
      ethernet {interface}:
        query:
          id: interface
          command:
            ls: /sys/class/net
        subnodes:
          vlan:
            multinode:
              template: vid
              node:
                properties:
                  description:
                    values:
                    - template: string
                  address:
                    values:
                    - literal: dhcp
                    - template: ipv4-cidr
        properties:
          description:
            values:
            - template: string
          address:
            values:
            - literal: dhcp
            - template: ipv4-cidr
          hardware:
            default:
            - query:
                id: mac
                command:
                  cat: /sys/class/net/{interface}/address
            deletable: false
            values:
            - template: mac
          mtu:
            default:
            - query:
                id: mtu
                command:
                  cat: /sys/class/net/{interface}/mtu
            deletable: false
            values:
            - range:
                lower:
                  inclusive: 1
                upper:
                  inclusive: 9000
  system:
    properties:
      hostname:
        default:
        - literal: router
        deletable: false
        values:
        - template: hostname
    subnodes:
      dns:
        properties:
          domain:
            values:
            - template: fqdn
          nameserver:
            multiple: true
            default:
            - literal: '1.1.1.1'
            - literal: '1.0.0.1'
            values:
            - template: fqdn
      ntp:
        properties:
          server:
            multiple: true
            default:
            - literal: 1.pool.ntp.org
            - literal: 2.pool.ntp.org
            - literal: 3.pool.ntp.org
            - literal: 4.pool.ntp.org
            values:
            - template: fqdn
      users:
        subnodes:
          user:
            properties:
              password:
                values:
                - template: string
            subnodes:
              ssh-keys:
                properties:
                  key:
                    multiple: true
                    values:
                    - template: ssh-key