[package]
name = "rp_common"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
rp_error = { path = "../rp_error" }
regex-automata = "0.1.8"
lazy_static = "1.4.0"
