[package]
name = "rp_common"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
regex-automata = "0.1.8"
lazy_static = "1.4.0"
anyhow = "1.0.22"
thiserror = "1.0.6"
strum = "0.16.0"
strum_macros = "0.16.0"
