[package]
name = "common"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_yaml = "0.8.9"
serde_cbor = "0.9"
regex = "1"
