[package]
name = "rp_shell"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
build = "build_schema.rs"

[dependencies]
rp_schema = { path = "../rp_schema" }
rp_config = { path = "../rp_config" }
rp_common = { path = "../rp_common" }
command_metadata = { path = "../command_metadata" }
enum_dispatch = "0.1.4"
termion = "1.5.3"
chrono = "0.4.9"
anyhow = "1.0.15"
thiserror = "1.0.3"

[build-dependencies]
rp_schema = { path = "../rp_schema" }
